const questions = [
  { word: "supply", synonym: "provide", meaning: "ထောက်ပံ့သည်" },
  { word: "stop from happening", synonym: "prevent", meaning: "တားဆီးသည်" },
  { word: "method", synonym: "system", meaning: "နည်းလမ်း" },
  { word: "rotting", synonym: "decaying", meaning: "ပုပ်နေသော" },
  { word: "spreads", synonym: "scoops", meaning: "ပျံ့နှံ့သည်" },
  { word: "held", synonym: "stored", meaning: "သိုလှောင်ထားသည်" },
  {
    word: "channels in the earth",
    synonym: "gullies",
    meaning: "မြေဆီလွှာတွင်းလမ်းကြောင်းများ",
  },
  {
    word: "the bringing back to a usable condition",
    synonym: "reclamation",
    meaning: "ပြန်လည်ထိန်းသိမ်းခြင်း",
  },
  { word: "used for", synonym: "devoted to", meaning: "အသုံးပြုသည်" },
  {
    word: "keep in existence",
    synonym: "conserve",
    meaning: "ထိန်းသိမ်းထားသည်",
  },
  { word: "called", synonym: "known as", meaning: "ခေါ်သည်" },
  { word: "descriptions", synonym: "accounts", meaning: "ဖော်ပြချက်များ" },
  { word: "mixed", synonym: "mingled", meaning: "ရောနှောထားသော" },
  {
    word: "the holy separate hairs",
    synonym: "sacred strands of hairs",
    meaning: "သန့်ရှင်းသောဆံပင်များ",
  },
  { word: "given", synonym: "presented", meaning: "ပေးအပ်ခဲ့သည်" },
  { word: "place", synonym: "site", meaning: "နေရာ" },
  { word: "helped", synonym: "aided", meaning: "ကူညီခဲ့သည်" },
  {
    word: "that had existed before",
    synonym: "preceding",
    meaning: "အရင်ကရှိခဲ့သော",
  },
  { word: "top", synonym: "tip", meaning: "ထိပ်" },
  { word: "makes up", synonym: "forms", meaning: "ဖွဲ့စည်းသည်" },
  {
    word: "moved farther away",
    synonym: "receded",
    meaning: "အဝေးသို့ဆွဲထွက်သွားသည်",
  },
  { word: "region", synonym: "district", meaning: "ဒေသ" },
  { word: "small area of land", synonym: "patch", meaning: "မြေပြင်အနည်းငယ်" },
  { word: "increasing", synonym: "extending", meaning: "တိုးချဲ့ခြင်း" },
  { word: "power", synonym: "authority", meaning: "အာဏာ" },
  { word: "capture", synonym: "seize", meaning: "ဖမ်းဆီးသည်" },
  { word: "in addition to", synonym: "besides", meaning: "အပြင်" },
  { word: "group of houses", synonym: "settlement", meaning: "နေအိမ်စု" },
  { word: "unimportant", synonym: "insignificant", meaning: "အရေးမကြီးသော" },
  { word: "made beautiful", synonym: "decorated", meaning: "အလှဆင်ထားသော" },
  { word: "covered with gold", synonym: "gilded", meaning: "ရွှေဖုံးထားသော" },
  { word: "obtained", synonym: "achieved", meaning: "ရရှိခဲ့သည်" },
  { word: "importance", synonym: "significance", meaning: "အရေးကြီးမှု" },
  {
    word: "not very big but very small",
    synonym: "fair",
    meaning: "အသင့်အတင့်",
  },
  { word: "in the direction of", synonym: "towards", meaning: "သို့" },
  { word: "most beautiful", synonym: "fairest", meaning: "အလှဆုံး" },
  {
    word: "surface of the land",
    synonym: "land surface",
    meaning: "မြေပြင်မျက်နှာပြင်",
  },
  { word: "areas", synonym: "regions", meaning: "ဒေသများ" },
  {
    word: "made up mainly",
    synonym: "composed chiefly",
    meaning: "အဓိက ဖွဲ့စည်းထားသည်",
  },
  {
    word: "that has to be continued for a long time",
    synonym: "sustained",
    meaning: "ကြာရှည်စွာ ဆက်လက်လုပ်ဆောင်သည့်",
  },
  {
    word: "did not have the ability to continue to do something",
    synonym: "lacked perseverance",
    meaning: "စွမ်းအားမရှိခြင်း၊ စောင့်ရှောက်မနိုင်ခြင်း",
  },
  { word: "usual", synonym: "customary", meaning: "အမြဲတမ်း ဖြစ်နေကျ" },
  { word: "border", synonym: "edge", meaning: "နယ်နိမိတ်၊ အနား" },
  { word: "rest of the snare", synonym: "remaining", meaning: "ကျန်ရှိသော" },
  {
    word: "blows",
    synonym: "impacts",
    meaning: "အကျိုးသက်ရောက်မှုများ၊ ထိခိုက်မှုများ",
  },
  { word: "began", synonym: "started", meaning: "စတင်ခဲ့သည်" },
  { word: "destroyed", synonym: "consumed", meaning: "ဖျက်ဆီးခဲ့သည်" },
  { word: "swallowed up", synonym: "engulfed", meaning: "မြုပ်နှံခဲ့သည်" },
  { word: "falling down", synonym: "collapsing", meaning: "ပေါ်ကျနေသော" },
  { word: "abilities", synonym: "skills", meaning: "စွမ်းရည်များ" },
  { word: "happen", synonym: "take place", meaning: "ဖြစ်ပွားသည်" },
  { word: "seen or heard", synonym: "experienced", meaning: "ကြုံတွေ့ခဲ့သည်" },
  { word: "kinds", synonym: "forms", meaning: "အမျိုးအစားများ" },
  { word: "judged", synonym: "considered", meaning: "စဉ်းစားခဲ့သည်" },
  { word: "joined", synonym: "connected", meaning: "ချိတ်ဆက်ခဲ့သည်" },
  { word: "need", synonym: "require", meaning: "လိုအပ်သည်" },
  {
    word: "in a way that has not been done before",
    synonym: "original",
    meaning: "မူရင်း၊ မိမိထူးခြားသော",
  },
  {
    word: "laws and qualities",
    synonym: "principles",
    meaning: "စည်းမျဉ်းစည်းကမ်းများ",
  },
  { word: "used for", synonym: "applied to", meaning: "အသုံးချသည်" },
  {
    word: "that have a practical purpose",
    synonym: "functional",
    meaning: "အကျိုးရှိသည့်",
  },
  { word: "expression", synonym: "term", meaning: "အသုံးအနှုန်း၊ စကားလုံး" },
  { word: "actions", synonym: "concerned", meaning: "လုပ်ဆောင်ချက်များ" },
  { word: "last", synonym: "survive", meaning: "ရှင်သန်ခဲ့သည်" },
  {
    word: "opposite to that in which the hands",
    synonym: "counter-clockwise",
    meaning: "နာရီလက်တည့်မဲ့ဦးတည်ခြင်း",
  },
  {
    word: "bring into action",
    synonym: "exerts",
    meaning: "အသုံးချသည်၊ သုံးစွဲသည်",
  },
  { word: "able to be seen", synonym: "visible", meaning: "မြင်နိုင်သော" },
  { word: "strength", synonym: "intensity", meaning: "တင်းမာမှု၊ အား" },
  { word: "comes near", synonym: "approaches", meaning: "နီးစပ်လာသည်" },
  { word: "is made up", synonym: "consists", meaning: "ဖွဲ့စည်းထားသည်" },
  {
    word: "very small spot",
    synonym: "a tiny speck",
    meaning: "အလွန်သေးငယ်သောအရိပ်",
  },
  { word: "turn round", synonym: "rotate", meaning: "လှည့်သည်" },
  { word: "travel round", synonym: "revolve round", meaning: "လှည့်ပတ်သည်" },
  {
    word: "turn round very fast",
    synonym: "spin",
    meaning: "လျင်မြန်စွာ လှည့်သည်",
  },
  { word: "bordered", synonym: "lined", meaning: "ခြံနယ်များထားသည်" },
  { word: "full of people", synonym: "crowded", meaning: "လူနည်းမဲ့၊ လူထူသော" },
  {
    word: "enough (verb to be + adj)",
    synonym: "sufficient",
    meaning: "လုံလောက်သော",
  },
  {
    word: "enough (adv+main verb)",
    synonym: "sufficiently",
    meaning: "လုံလောက်စွာ",
  },
  { word: "point", synonym: "stage", meaning: "အဆင့်" },
  { word: "direction", synonym: "course", meaning: "ဦးတည်ချက်" },
  { word: "immediately", synonym: "directly", meaning: "ချက်ချင်း" },
  { word: "acted", synonym: "served", meaning: "လုပ်ဆောင်ခဲ့သည်" },
  { word: "new", synonym: "fresh", meaning: "သစ်သော" },
  { word: "main", synonym: "leading", meaning: "အဓိက" },
  {
    word: "make us able",
    synonym: "enables",
    meaning: "ခွင့်ပြုသည်၊ အင်အားပေးသည်",
  },
  { word: "effective", synonym: "efficient", meaning: "ထိရောက်သော" },
  { word: "consider it as true", synonym: "assume", meaning: "ယူဆသည်" },
  { word: "stays steady", synonym: "remains stable", meaning: "တည်ငြိမ်နေသည်" },
  { word: "slope", synonym: "lean", meaning: "ထောင့်" },
  { word: "satisfaction", synonym: "fulfillment", meaning: "ကျေနပ်မှု" },
  {
    word: "that is as old as the ages",
    synonym: "age-old",
    meaning: "အခေတ်အမျိုးအစားအဟောင်း",
  },
  { word: "finished", synonym: "over", meaning: "ပြီးဆုံးသည်" },
  { word: "drive away", synonym: "banish", meaning: "အပြင်းအထန်သွားပစ်သည်" },
  {
    word: "land like a tongue",
    synonym: "a tongue of land",
    meaning: "ဧရိယာပုံသဏ္ဍာန် မြေ",
  },
  { word: "stretches", synonym: "extends", meaning: "ချဲ့ထွင်သည်" },
  {
    word: "region that allow living things to grow well",
    synonym: "fertile region",
    meaning: "ပေါက်ပျော်သောဒေသ",
  },
  { word: "behave according to", synonym: "respond", meaning: "တုံ့ပြန်သည်" },
  { word: "about", synonym: "approximately", meaning: "လတ်တလောအနည်းအကျဉ်း" },
  { word: "were / was", synonym: "existed", meaning: "ရှိခဲ့သည်" },
  { word: "made up", synonym: "formed", meaning: "ဖွဲ့စည်းထားသည်" },
  { word: "were made came into", synonym: "existence", meaning: "တည်ရှိလာသည်" },
  { word: "period", synonym: "time", meaning: "ကာလ" },
  { word: "changed", synonym: "transformed", meaning: "ပြောင်းလဲသွားသည်" },
  { word: "very great", synonym: "immense", meaning: "အလွန်ကြီးမားသော" },
  {
    word: "break into different parts",
    synonym: "split",
    meaning: "ခွဲထွက်သည်",
  },
  { word: "broken pieces", synonym: "fragments", meaning: "အစိတ်အပိုင်းများ" },
  { word: "beginning", synonym: "originating", meaning: "အစပိုင်း" },
  { word: "started", synonym: "began", meaning: "စတင်ခဲ့သည်" },
  { word: "rotted", synonym: "decayed", meaning: "ပုပ်နေသော" },
  { word: "mixed", synonym: "mingled", meaning: "ရောနှောထားသော" },
  { word: "powder", synonym: "dust", meaning: "မှုန်" },
  { word: "separate stages", synonym: "by degrees", meaning: "အဆင့်ဆင့်" },
  { word: "words", synonym: "terms", meaning: "စကားလုံးများ" },
{ word: "characteristics", synonym: "features", meaning: "အင်္ဂါရပ်များ" },
{ word: "enable this feature to be seen", synonym: "display this trait", meaning: "ဤအင်္ဂါရပ်ကို ပြသသည်" },
{ word: "separate", synonym: "single out", meaning: "ခွဲထုတ်သည်" },
{ word: "inside their bodies", synonym: "internal", meaning: "ကိုယ်တွင်း" },
{ word: "at an unchanging point", synonym: "a constant level", meaning: "အတည့်တည်နေသောအဆင့်" },
{ word: "very great and sudden", synonym: "drastic", meaning: "လွန်စွာကြီးမားပြီး လျင်မြန်သော" },
{ word: "not a characteristic only mammals possess", synonym: "hardly unique", meaning: "မူရင်းထူးခြားမှုမရှိသော" },
{ word: "resist greatly differing limits", synonym: "withstand an extreme range", meaning: "အကန့်အသတ်ကြီးများကို ခံနိုင်ရည်ရှိသည်" },
{ word: "unwilling to move", synonym: "listless", meaning: "မလှုပ်မရွားသော" },
{ word: "eating very frequently", synonym: "continual nourishment", meaning: "မကြာခဏစားသောက်ခြင်း" },
{ word: "yearly", synonym: "annual", meaning: "နှစ်စဉ်" },
{ word: "height", synonym: "altitude", meaning: "အမြင့်" },
{ word: "cut down", synonym: "felled", meaning: "လှန်ချက်ပြတ်သည်၊ ချည်ထုတ်သည်" },
{ word: "is greater than", synonym: "exceeds", meaning: "ကျော်လွန်သည်" },
{ word: "usually", synonym: "generally", meaning: "အားလုံးအဖြစ်" },
{ word: "main", synonym: "principal", meaning: "အဓိက" },
{ word: "ability to last for a long time", synonym: "durability", meaning: "တည်တံ့မှု၊ ခံနိုင်ရည်" },
{ word: "examples", synonym: "instances", meaning: "ဥပမာများ" },
{ word: "perform", synonym: "carry out", meaning: "ဆောင်ရွက်သည်" },
{ word: "work", synonym: "task", meaning: "တာဝန်၊ လုပ်ငန်း" },
{ word: "keeps", synonym: "safeguards", meaning: "ကာကွယ်ထိန်းသိမ်းသည်" },
{ word: "making sure", synonym: "ensuring", meaning: "သေချာစေရန်" },
{ word: "fully grown", synonym: "mature", meaning: "ပြည့်စုံပြီး ကြီးပြင်းသော" },
{ word: "central park", synonym: "core", meaning: "အဓိက အစွန်း" },
{ word: "stopping", synonym: "preventing", meaning: "တားဆီးခြင်း" },
{ word: "performs", synonym: "carries out", meaning: "ဆောင်ရွက်သည်" },
{ word: "selling", synonym: "marketing", meaning: "ရောင်းချခြင်း" },
{ word: "unable to be reached by", synonym: "inaccessible to", meaning: "ရောက်မရနိုင်သော" },
{ word: "necessary", synonym: "essential", meaning: "လိုအပ်သော" },
{ word: "pulling", synonym: "hauling", meaning: "ဆွဲခြင်း" },
{ word: "able to float", synonym: "capable of floating", meaning: "ရေထဲပေါ်တွင်ထုန်နိုင်သော" },
{ word: "with the progress of time", synonym: "in the course of time", meaning: "အချိန်ကြာမြင့်မှုအတွင်း" },
{ word: "speed", synonym: "rate", meaning: "အမြန်နှုန်း" },
{ word: "to a great extent", synonym: "on a large scale", meaning: "ကြီးမားစွာ" },
{ word: "without any break", synonym: "continuous", meaning: "မရပ်တန့်သော" },
{ word: "steady", synonym: "regular", meaning: "စည်းမျဉ်းတကျ" },
{ word: "decisive", synonym: "crucial", meaning: "အရေးပါသော" },
{ word: "great variety", synonym: "wide range", meaning: "အမျိုးမျိုးစွာ" },
{ word: "tasks", synonym: "duties", meaning: "တာဝန်များ" },
{ word: "stop", synonym: "keep", meaning: "တားဆီးသည်" },
{ word: "stop harming", synonym: "prevent damaging", meaning: "ထိခိုက်မှုကိုကာကွယ်သည်" },
{ word: "make larger area", synonym: "increase extent", meaning: "ဧရိယာကိုချဲ့ထွင်သည်" },
{ word: "a person who wishes to be a forester", synonym: "potential forester", meaning: "သစ်တောစောင့်ကြပ်သူဖြစ်လိုသူ" },
{ word: "each year", synonym: "yearly", meaning: "နှစ်စဉ်" },
{ word: "that will last", synonym: "permanent", meaning: "အမြဲတမ်းရှိနေသော" },
{ word: "usually", synonym: "normally", meaning: "သာမန်အားဖြင့်" },
{ word: "not enough", synonym: "insufficient", meaning: "လုံလောက်မှုမရှိသော" },
{ word: "slows", synonym: "retards", meaning: "နှေးစေသည်" },
{ word: "finally stops", synonym: "eventually prevents", meaning: "နောက်ဆုံးတွင်တားဆီးသည်" },
{ word: "needs", synonym: "requirements", meaning: "လိုအပ်ချက်များ" },
{ word: "exactly", synonym: "just", meaning: "တိကျမှန်ကန်စွာ" },
{ word: "quantities", synonym: "amounts", meaning: "ပမာဏများ" },
{ word: "methods", synonym: "means", meaning: "နည်းလမ်းများ" },
{ word: "times", synonym: "periods", meaning: "ကာလများ" },
{ word: "inside", synonym: "within", meaning: "အတွင်း" },
{ word: "making use of", synonym: "utilizing", meaning: "အသုံးချခြင်း" },
{ word: "in other conditions", synonym: "otherwise", meaning: "အခြားအခြေအနေများတွင်" },
{ word: "control", synonym: "govern", meaning: "ထိန်းချုပ်သည်" },
{ word: "throughout the year", synonym: "perennial", meaning: "တစ်နှစ်လုံး" },
{ word: "that do not happen very often", synonym: "very rare intervals", meaning: "အလွန်နည်းသောအကြိမ်များ" },
{ word: "times", synonym: "intervals", meaning: "ကြားကာလများ" },
{ word: "defence", synonym: "protection", meaning: "ကာကွယ်မှု" },
{ word: "dry", synonym: "arid", meaning: "ခြောက်သွေ့သော" },
{ word: "each year", synonym: "annually", meaning: "နှစ်စဉ်" },
{ word: "sank", synonym: "subsided", meaning: "ကျဆင်းသွားသည်" },
{ word: "simple", synonym: "primitive", meaning: "ရိုးရှင်းသော" },
{ word: "less plentiful", synonym: "scarcer", meaning: "နည်းပါးသော" },
{ word: "that would be able to produce", synonym: "productive", meaning: "ထုတ်လုပ်နိုင်သော" },
];
